package com.example.mybookshopapp.struct.book;

import com.example.mybookshopapp.struct.author.AuthorEntity;
import com.example.mybookshopapp.struct.book.file.BookFileEntity;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import org.hibernate.annotations.ColumnDefault;

import java.sql.Date;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name="books")
@Schema(description = "entity representing a book")
public class BookEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(nullable = false)
    @Schema(description = "id generated by db automatically")
    private Integer id;
    @Column(name = "pub_date",nullable = false)
    @Schema(description = "date of book publication")
    private Date pubDate;
    @Column(name = "is_bestseller", nullable = false)
    @Schema(description = "if isBestseller = 1 then book is bestseller")
    private short isBestseller;
    @Column(nullable = false)
    @Schema(description = "mnemotical identity sequence of characters")
    private String slug;
    @Column(nullable = false)
    @Schema(description = "books title")
    private String title;

    @Schema(description = "image url of book")
    private String image;

    @Column(columnDefinition = "TEXT")
    @Schema(description = "books description text")
    private String description;
    @Column(nullable = false)
    @Schema(description = "price of book")
    private Integer price;
    @Column(nullable = false)
    @ColumnDefault("0")
    @Schema(description = "books discount")
    private short discount;

    public List<BookFileEntity> getBookFileList() {
        return bookFileEntityList;
    }

    public void setBookFileEntityList(List<BookFileEntity> bookFileEntityList) {
        this.bookFileEntityList = bookFileEntityList;
    }

    @OneToMany(mappedBy = "book")
    private List<BookFileEntity> bookFileEntityList = new ArrayList<>();
    public AuthorEntity getAuthor() {
        return author;
    }

    public void setAuthor(AuthorEntity author) {
        this.author = author;
    }

    @ManyToOne
    @JoinColumn(name = "author_id")
    //@JsonIgnore
    private AuthorEntity author;
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Date getPubDate() {
        return pubDate;
    }

    public void setPubDate(Date pubDate) {
        this.pubDate = pubDate;
    }

    public short getIsBestseller() {
        return isBestseller;
    }

    public void setIsBestseller(short isBestseller) {
        this.isBestseller = isBestseller;
    }

    public String getSlug() {
        return slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getPrice() {
        return price;
    }

    public void setPrice(Integer price) {
        this.price = price;
    }

    public short getDiscount() {
        return discount;
    }

    public void setDiscount(short discount) {
        this.discount = discount;
    }
}
