UPDATE book_app.users set password = 'zU7<VEz!C''4' where id = 1;
UPDATE book_app.users set password = 'jN5#|vGH=G&RqE' where id = 2;
UPDATE book_app.users set password = 'uB2#MC!YYotIV' where id = 3;
UPDATE book_app.users set password = 'yW7!Qhm%\<*qy' where id = 4;
UPDATE book_app.users set password = 'vU4+hMTz77J5rXzU' where id = 5;
UPDATE book_app.users set password = 'oX5%|P70H$DQ__Vw' where id = 6;
UPDATE book_app.users set password = 'kC2+TXis*' where id = 7;
UPDATE book_app.users set password = 'uG6,r55ytLL' where id = 8;
UPDATE book_app.users set password = 'fR7_=91y{' where id = 9;
UPDATE book_app.users set password = 'kL0+NvPjt7V>M$' where id = 10;
UPDATE book_app.users set password = 'yD8{d2#1vl%' where id = 12;
UPDATE book_app.users set password = 'kX1~f69n&Z' where id = 13;
UPDATE book_app.users set password = 'zK0<3~!/1' where id = 14;
UPDATE book_app.users set password = 'vW0+1y5p!X/lnX>P' where id = 15;
UPDATE book_app.users set password = 'sJ7~7lMde.Q' where id = 16;
UPDATE book_app.users set password = 'tU0(B"PoUSYy"'where id = 17;
UPDATE book_app.users set password = 'oX3*_".''mBFM,f5'where id = 18;
UPDATE book_app.users set password = 'uP7}7Cy~(Pi?xw@' where id = 19;
UPDATE book_app.users set password = 'zC1#"ae=pe*Fj!' where id = 20;
UPDATE book_app.users set password = 'dB0/D''|"8~1''3' where id = 21;
UPDATE book_app.users set password = 'pT3_!7\GzY&ZV4'where id = 21;
UPDATE book_app.users set password = 'lQ8=?.(=H>HTj'where id = 22;
UPDATE book_app.users set password = 'qR5/p5u@&''oL'where id = 23;
UPDATE book_app.users set password = 'wW2$Nn>k'where id = 24;
UPDATE book_app.users set password = 'gZ7>{t?*{vul(P'where id = 25;
UPDATE book_app.users set password = 'vX26jL(dsHTtk('where id = 26;
UPDATE book_app.users set password = 'iX5?ONiAClR'where id = 27;
UPDATE book_app.users set password = 'bY6''KdxNs_c'where id = 28;
UPDATE book_app.users set password = 'kY5{Gz~F3.D'where id = 29;
UPDATE book_app.users set password = 'gD0(|K|\1Yx.|'where id = 30;
UPDATE book_app.users set password = 'lF8{ZeeQvy'where id = 31;
UPDATE book_app.users set password = 'oD5+ruBqQI5'where id = 32;
UPDATE book_app.users set password = 'bP0_|QTt}u92'where id = 33;
UPDATE book_app.users set password = 'nN2''d@<xwO\(PF}a'where id = 34;
UPDATE book_app.users set password = 'oW8}NB55b'where id = 35;
UPDATE book_app.users set password = 'dK0,s1ja90*tL$'where id = 36;
UPDATE book_app.users set password = 'qO4`|BL`HB`'where id = 37;
UPDATE book_app.users set password = 'uH6%B~&I'where id = 38;
UPDATE book_app.users set password = 'lT0+PnuS~'where id = 39;
UPDATE book_app.users set password = 'pE0}Y?Kwp@$Eq~J'where id = 40;
UPDATE book_app.users set password = 'aT1=YWsRU'where id = 41;
UPDATE book_app.users set password = 'tX3''A*1rBT``'where id = 42;
UPDATE book_app.users set password = 'iM7%''I~ufT\UYWk~'where id = 43;
UPDATE book_app.users set password = 'jK5~sVw}`l'where id = 44;
UPDATE book_app.users set password = 'iW0{hM$O'where id = 45;
UPDATE book_app.users set password = 'cQ7@v@Gqa'where id = 46;
UPDATE book_app.users set password = 'vN8`''0D|+Xs0E'where id = 47;
UPDATE book_app.users set password = 'dG3""wUX$%aM'where id = 48;
UPDATE book_app.users set password = 'mF7&nr}LE'where id = 49;
UPDATE book_app.users set password = 'tM8%1VDkv&,</w'where id = 50;
UPDATE book_app.users set password = 'sZ4"~n_K%42W='where id = 51;
UPDATE book_app.users set password = 'jS4\mivVe'where id = 52;
UPDATE book_app.users set password = 'qG6{Pl}Zd4'where id = 53;
UPDATE book_app.users set password = 'bC0_IE,d?Zq<'where id = 54;
UPDATE book_app.users set password = 'qJ1>.c*(Mfm'where id = 55;
UPDATE book_app.users set password = 'eC5ehwXpxe'where id = 56;
UPDATE book_app.users set password = 'vQ8%EomaL~'where id = 57;
UPDATE book_app.users set password = 'jD0<FNa!~}'where id = 58;
UPDATE book_app.users set password = 'pE1"PYu''2T..c'where id = 59;
UPDATE book_app.users set password = 'zR4!A(}Uo3x'where id = 60;
UPDATE book_app.users set password = 'jD0$UlX`3N9q'where id = 61;
UPDATE book_app.users set password = 'nK0\hTQTQL%OBCg'where id = 62;
UPDATE book_app.users set password = 'pZ5>fsv$O@7|7'where id = 63;
UPDATE book_app.users set password = 'eZ2>&k*a~ZrABZ'where id = 64;
UPDATE book_app.users set password = 'vY1.cbbJ3AX%Zn&'where id = 65;
UPDATE book_app.users set password = 'wS4(HzWtyG*hP'where id = 66;
UPDATE book_app.users set password = 'dU7%u0!4emissI<L'where id = 67;
UPDATE book_app.users set password = 'lX6(Y@=6'where id = 68;
UPDATE book_app.users set password = 'eE8/S&B/l$tqe'where id = 69;
UPDATE book_app.users set password = 'xS0@+.gJpEWTP&6'where id = 70;
UPDATE book_app.users set password = 'tF2&D<48$f/SJ'where id = 71;
UPDATE book_app.users set password = 'zD5_5G3A<Ex4E'where id = 72;
UPDATE book_app.users set password = 'sL2+&@t6_4sO'where id = 73;
UPDATE book_app.users set password = 'cW2~G+&+r'where id = 74;
UPDATE book_app.users set password = 'fU16g>S(+zMHUi'where id = 75;
UPDATE book_app.users set password = 'oI2>t*kjp}VWh>.'where id = 76;
UPDATE book_app.users set password = 'rZ4%$cArSZs}+'where id = 77;
UPDATE book_app.users set password = 'gB4+0g1gC'where id = 78;
UPDATE book_app.users set password = 'aV2,BLM4867Nc'where id = 79;
UPDATE book_app.users set password = 'oO1=Wq>Lz#'where id = 80;
UPDATE book_app.users set password = 'xL8!g+/Lm4d"cQic'where id = 81;
UPDATE book_app.users set password = 'kK5#l2IV_P'where id = 82;
UPDATE book_app.users set password = 'rQ6}$06}~Vl*#'where id = 83;
UPDATE book_app.users set password = 'zF6+hAl|"1'where id = 84;
UPDATE book_app.users set password = 'oF0&`#%8*}(t6WA'where id = 85;
UPDATE book_app.users set password = 'xL5"T7%S,iq&'where id = 86;
UPDATE book_app.users set password = 'lA4*#\RP.M}Kla'where id = 87;
UPDATE book_app.users set password = 'yK9(k40*l&'where id = 88;
UPDATE book_app.users set password = 'tT2"d_V(L'where id = 89;
UPDATE book_app.users set password = 'kT9>uz?9'where id = 90;
UPDATE book_app.users set password = 'hP1<pDtwW$'where id = 91;
UPDATE book_app.users set password = 'cA5/A5d2"p'where id = 92;
UPDATE book_app.users set password = 'dW3|Fz"Sl'where id = 93;
UPDATE book_app.users set password = 'gP0$je$M'where id = 94;
UPDATE book_app.users set password = 'aY3~A,RUaE4XuXa/'where id = 95;
UPDATE book_app.users set password = 'yO6/?2"uN7zm,'''where id = 96;
UPDATE book_app.users set password = 'oK4lN}qc}wq4r'where id = 97;
UPDATE book_app.users set password = 'hY9{TlHivREfd'where id = 98;
UPDATE book_app.users set password = 'rB2_6gA"J5KBWh>'where id = 99;
UPDATE book_app.users set password = 'wM6"PDz6+=NZs'where id = 100;